- hosts: '{{ machine }}'
  become: true
  tasks:
    - name: 'create/remove empty file'
      file:
        path: '/home/ansible/test_file.txt'
        state: '{{ state }}'
        owner: ansible
        group: ansible
        mode: 0644

