- hosts: '{{ machine }}'
  become: true
  tasks:
    - name: 'remove user testuser'
      user:
        name: 'testuser'
        state: absent
        remove: yes
        force: yes

    - name: 'remove sudoers testuser'
      file:
        path: '/etc/sudoers.d/testuser'
        state: absent
