---
# Variable configuration.
- include_tasks: variables.yml

# Setup/install tasks.
- include_tasks: unset-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: unset-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: unset-Archlinux.yml
  when: ansible_os_family == 'Archlinux'

- name: Check if MySQL packages were installed.
  set_fact:
    mysql_install_packages: "{{ (rh_mysql_install_packages is defined and rh_mysql_install_packages.changed)
      or (deb_mysql_install_packages is defined and deb_mysql_install_packages.changed)
      or (arch_mysql_install_packages is defined and arch_mysql_install_packages.changed) }}"

# Configure MySQL.
- include_tasks: remove.yml
