---
#- name: Get MySQL version.
#  command: 'mysql --version'
#  register: mysql_cli_version
#  changed_when: false
#  check_mode: false

- name: Remove my.cnf global MySQL configuration
  file:
    path: "{{ mysql_config_file }}"
    state: absent

- name: Remove mysql include directory
  file:
    path: "{{ mysql_config_include_dir }}"
    state: absent

- name: Remove datadir
  file:
    path: "{{ mysql_datadir }}"
    state: absent

- name: Remove log dir
  file:
    path: "{{ mysql_logdir }}"
    state: absent

- name: Remove temporary conf
  file:
    path: '/root/.my.cnf'
    state: absent
