---
- name: Ensure MySQL packages are installed.
  yum:
    name: '{{ mysql_packages }}'
    state: absent
    enablerepo: '{{ mysql_enablerepo | default(omit, true) }}'
  register: rh_mysql_install_packages
