---
dependencies: []

galaxy_info:
  role_name: mysql_setup
  author: NRE
  description: MySQL server for RHEL/CentOS and Debian/Ubuntu.
  company: "NRE Corp"
  license: "NRE Licnce"
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Archlinux
      versions:
        - all
  galaxy_tags:
    - database
    - mysql
    - mariadb
    - db
    - sql
